spring.application.name=videostreaming

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=root

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

thumbnail_dir=C:/videostreaming-uploads/thumbnails/
video_dir=C:/videostreaming-uploads/videos/

jwt.secret=c25944d6b8cabe632ade950a9463aabcd5c45ba987c3b7a4ce4c603fb82c14bd